name: Run wot-py tests
on: [push, pull_request]
jobs:
  python-37:
    uses: ./.github/workflows/run-python-tests.yaml
    with:
      python-version-tag: "3.7"
  python-38:
    needs:
      - python-37
    uses: ./.github/workflows/run-python-tests.yaml
    with:
      python-version-tag: "3.8"
  python-39:
    needs:
      - python-37
      - python-38
    uses: ./.github/workflows/run-python-tests.yaml
    with:
      python-version-tag: "3.9"
  python-310:
    needs:
      - python-37
      - python-38
      - python-39
    uses: ./.github/workflows/run-python-tests.yaml
    with:
      python-version-tag: "3.10"
  python-311:
    needs:
      - python-37
      - python-38
      - python-39
      - python-310
    uses: ./.github/workflows/run-python-tests.yaml
    with:
      python-version-tag: "3.11"
